### ISSUE TITLE
search results page - too little margin between separator lines and text

### ISSUE THREAD

**Issue by Dan-KeduTesting** [Buckinghamshire-Digital-Service/hr-service-desk-alpha#103]
can margin be 30px between horizonal line and text please? (both above and below)

see screenshot for margin in question 
![search_results_page_-_too_little_margin_between_seporator_lines_and_text](https://user-images.githubusercontent.com/2722522/65515935-fd44f300-ded7-11e9-87e1-2b550b1b9b97.png)

**Comment by enginehouse** [comment]
Increased in line with other margins
