### ISSUE TITLE
search results page - page title text font size too small on mobile.

### ISSUE THREAD

**Issue by Dan-KeduTesting** [Buckinghamshire-Digital-Service/hr-service-desk-alpha#105]
![search_results_page_-_page_title_text_font_size_too_small_on_mobile](https://user-images.githubusercontent.com/2722522/65516650-49dcfe00-ded9-11e9-8b4b-f40e98365a5e.png)

**Comment by enginehouse** [comment]
It is reusing an h3 size - which I think is the correct size rather than the new one - I think for consistency we should try and reduce the number of new sizes (the whole thing is a link after all)
