### ISSUE TITLE
search results page - searching on search page for something to short (2 chat) then no results does not show no results message

### ISSUE THREAD

**Issue by Dan-KeduTesting** [Buckinghamshire-Digital-Service/hr-service-desk-alpha#106]
1. search for something that returns results (e.g. holiday)
2. on search results page search for something too short such as "22"

actual result:
results dont update

expected:
should get no results displayed

**Comment by enginehouse** [comment]
Fixed

**Comment by enginehouse** [comment]
I don't think it matters if we show something for even a single letter. It's all cool
