### ISSUE TITLE
search results page - search textbox feels too wide

### ISSUE THREAD

**Issue by Dan-KeduTesting** [Buckinghamshire-Digital-Service/hr-service-desk-alpha#108]
can we have max width of 500px

![search_results_page_-_search_textbox_feels_too_wide](https://user-images.githubusercontent.com/2722522/65521265-d9d27600-dee0-11e9-9f38-c850d425de5e.png)

**Comment by enginehouse** [comment]
I chatted to Derek and he requested that it be this wide - going to drop this one
