### ISSUE TITLE
search results page - accessibility - if screenreader user search again they are not informed the page has updated

### ISSUE THREAD

**Issue by Dan-KeduTesting** [Buckinghamshire-Digital-Service/hr-service-desk-alpha#112]
if a search is performed on search results page can we add role=alert to the "x search results for y text" so this gets read to the screenreaser user

also if there are no result that add the role=alert to the no results message

**Comment by enginehouse** [comment]
What are your thoughts about aria-live for this?
https://www.w3.org/TR/wai-aria/#aria-live

**Comment by enginehouse** [comment]
@Dan-KeduTesting

**Comment by Dan-KeduTesting** [comment]
role=alert is equivalent to using aria-live=assertive (quote from https://www.w3.org/TR/WCAG20-TECHS/ARIA19.html)

so either but prefer role=alert

**Comment by enginehouse** [comment]
These have been added @Dan-KeduTesting
