### ISSUE TITLE
Search results page - when there are no results there should be more margin above first bullet point and between bullet points 

### ISSUE THREAD

**Issue by Dan-KeduTesting** [Buckinghamshire-Digital-Service/hr-service-desk-alpha#113]
see screenshot for margin in question 

![Search_results_page_-_when_there_are_no_results_there_should_be_more_margin_above_first_bullet_point_and_between_bullet_points](https://user-images.githubusercontent.com/2722522/65525217-130de480-dee7-11e9-9629-0028b396ed1a.png)

**Comment by enginehouse** [comment]
Sorted
