### ISSUE TITLE
Search results page - when there are no results there should be more margin between last bullet point  and footer

### ISSUE THREAD

**Issue by Dan-KeduTesting** [Buckinghamshire-Digital-Service/hr-service-desk-alpha#115]
see screenshot for margin in question 

![Search_results_page_-_when_there_are_no_results_there_should_be_more_margin_between_last_bullet_point__and_footer](https://user-images.githubusercontent.com/2722522/65525569-a3e4c000-dee7-11e9-8973-5e1d996bf0f6.png)

**Comment by enginehouse** [comment]
This is what I have got:
![Uploading Screenshot 2019-09-25 at 11.58.59.png…]()

**Comment by enginehouse** [comment]
This is what I have got:
![Screenshot 2019-09-25 at 11 58 59](https://user-images.githubusercontent.com/5637994/65595120-f37cc780-df8b-11e9-85d0-d236790a3990.png)
