### ISSUE TITLE
Search overlay - ie 11 - search textbox not displayed centrally aligned (currently search button falls of edge of screen)

### ISSUE THREAD

**Issue by Dan-KeduTesting** [Buckinghamshire-Digital-Service/hr-service-desk-alpha#125]
see screenshot 

![Search_overlay_-_ie_11_-_search_textbox_not_displayed_centerally_alligned_(currently_search_button_falls_of_edge_of_screen)](https://user-images.githubusercontent.com/2722522/65625415-b46a6880-dfc3-11e9-9d06-e1e459f3fe1b.png)

**Comment by enginehouse** [comment]
Fixed with #142
