### ISSUE TITLE
generic template - on mobile h2 and h3 text font size is too big

### ISSUE THREAD

**Issue by Dan-KeduTesting** [Buckinghamshire-Digital-Service/hr-service-desk-alpha#131]
font size is same as desktop but should be smaller 

(currently h2 and h3 font size is bigger then h1 on mob)

![generic_template_-_on_mobile_h2_and_h3_text_font_size_is_too_big](https://user-images.githubusercontent.com/2722522/65632979-ea631900-dfd2-11e9-9131-644a3d759ca6.png)

**Comment by enginehouse** [comment]
Fixed with a67f5fe6 Updating table styles
