### ISSUE TITLE
Mobile menu overlay - Firefox - X button overlaps menu text

### ISSUE THREAD

**Issue by Dan-KeduTesting** [Buckinghamshire-Digital-Service/hr-service-desk-alpha#134]
Firefox - Expand the hamburger menu

(you may need to refresh page on a resized browser window to see the hamburger menu)

Expected: X button - to close menu - is positioned at the top of the menu text.

Actual: X button is placed below the first menu item.
![Mobile_menu_-_firefox_-_X_button](https://user-images.githubusercontent.com/2722522/65671898-0355e380-e040-11e9-8a6d-ca76b825f939.png)

In fact, I am finding that this issue is occurring on PC - Chrome also.
This is definitely unexpected as it was not occurring on previous tests on Chrome.

![Mobile_menu_-_chrome_-_X_button](https://user-images.githubusercontent.com/2722522/65672066-53cd4100-e040-11e9-8b63-a9b7c8552391.png)

Needs further investigation on actual mobile devices.

**Comment by Dan-KeduTesting** [comment]
Also true on MS Edge

**Comment by Dan-KeduTesting** [comment]
Further investigation shows that this is occurring when the cookie notice is still present.

Once the cookie notice is dismissed, the X button appears in the correct position

**Comment by Dan-KeduTesting** [comment]
This is true on Samsung J7 - Chrome. The X is poorly positioned when the cookie notification is present. And becomes tidy once the cookie notice is dismissed

**Comment by Dan-KeduTesting** [comment]
Problem occurs in both portrait and in landscape oientation

**Comment by enginehouse** [comment]
@Dan-KeduTesting  - thanks, good clear notes there, very cool : )
