### ISSUE TITLE
Time off sick - IE11 - Open Word document - treated as a .zip file instead of as docx

### ISSUE THREAD

**Issue by Dan-KeduTesting** [Buckinghamshire-Digital-Service/hr-service-desk-alpha#141]
Time off sick

Page has a link to open / download 'self certification form (Word doc, 21k)'

Chrome, Firefox, MS Edge were each slightly different, but all resulted in opening the doc in my Office viewer package.

IE11 immediately describes the docx as a .zip file. When I choose to open it. It does so in my .zip package (winrar) and shows a selection of folders containing XML files. I never get to see the word doc.

**Comment by Dan-KeduTesting** [comment]
A similar link within:

https://d2r8w0gkpz98vq.cloudfront.net/time-off-sick/#illness-policy

Works fine in IE11

**Comment by enginehouse** [comment]
I created that one as a dummy content file and have now removed this - I think it will be fine from now on
