### ISSUE TITLE
Privacy - iphone portrait - table is crowded and untidy

### ISSUE THREAD

**Issue by Dan-KeduTesting** [Buckinghamshire-Digital-Service/hr-service-desk-alpha#144]
Privacy page contains a table with 3 columns, titled 'Data rights'.

The table is untidy and a little difficult to read.
The first column has very little content, but takes up a lot of space.
The 2nd column has the most content. This is squeezed into a tall column.
The 3 column has only 1 item, an email address that won't wrap and sticks out the right side of the  page when the page is first loaded.

It is all readable, and you can swipe across to see the full email address.
And you can resolve the issue by rotating to landscape. The table is now tidy and well layed out.

I'm not certain this issue needs resolving. But other tables, eg with more email addresses, or more content in any 1 column could look much worse

**Comment by Dan-KeduTesting** [comment]
![privacy - iphone - narrow table](https://user-images.githubusercontent.com/2722522/65699947-c22cf600-e076-11e9-88ef-b52852fc62cf.jpeg)

**Comment by Dan-KeduTesting** [comment]
Also true on Android - Samsung J7 - in portrait

**Comment by enginehouse** [comment]
Fixed - a content editing thing
