### ISSUE TITLE
details template - in expandable section text width is too wide (over 80 char per line)

### ISSUE THREAD

**Issue by Dan-KeduTesting** [Buckinghamshire-Digital-Service/hr-service-desk-alpha#159]
can we reduce line width to 600px on desktop

also below 768px viewports there are even more char per line. Can we have more left and right padding at this breakpoint to reduce line width

![below_768](https://user-images.githubusercontent.com/2722522/65815894-e14d9400-e1ec-11e9-9d90-2cad9c0a36c0.png)

**Comment by enginehouse** [comment]
reduced to max 600px wide
