### ISSUE TITLE
Contact page - page displays incorrect content after selecting 'ask now' button then selecting browser back button

### ISSUE THREAD

**Issue by Dan-KeduTesting** [Buckinghamshire-Digital-Service/hr-service-desk-alpha#163]
see screenshot below for what you see after selecting browser back button

![Contact_page_-_page_displays_incorrect_content_after_selecting_'ask_now'_button_then_selecting_browser_back_button](https://user-images.githubusercontent.com/2722522/65820438-f7754780-e220-11e9-81f7-0c58c1cde581.png)

**Comment by enginehouse** [comment]
I can't reproduce this
