### ISSUE TITLE
privacy page - mobile - in narrow resolution mobile (310px) text gets cut off in table

### ISSUE THREAD

**Issue by Dan-KeduTesting** [Buckinghamshire-Digital-Service/hr-service-desk-alpha#166]
see screenshot 

![privacy_page_-_mobile_-_in_narrow_resolution_mobiled_(310px)_text_gets_cut_off_in_table](https://user-images.githubusercontent.com/2722522/65820617-48863b00-e223-11e9-8dd1-ac96abb896c3.png)

**Comment by enginehouse** [comment]
It's supposed to - it is set to `scroll: auto` to allow for scrolling using a swioe on mobile
