### ISSUE TITLE
Privacy page - mobile - table columns equal with but there is more content in right hand column

### ISSUE THREAD

**Issue by Dan-KeduTesting** [Buckinghamshire-Digital-Service/hr-service-desk-alpha#167]
this is a bit of an accessibility issue due to narrow column and text wrapping to loads of lines (harder to read for dyslexic users)

can right hand column be wider please?

![Privacy_page_-_mobile_-_table_coumns_equel_with_but_there_is_more_content_in_right_hand_column](https://user-images.githubusercontent.com/2722522/65820654-ac106880-e223-11e9-8a42-d7b17592c9a8.png)

**Comment by enginehouse** [comment]
I broke a long word that needed some spaces and this is fixed now
