### ISSUE TITLE
Privacy page - column headers should be <th> html tag and not <td>

### ISSUE THREAD

**Issue by Dan-KeduTesting** [Buckinghamshire-Digital-Service/hr-service-desk-alpha#173]
see screenshot for code in question 

![Privacy_page_-_column_headers_should_be_th_html_tag_and_not_td](https://user-images.githubusercontent.com/2722522/65869315-1df6c800-e372-11e9-9cee-ee3a0ece05eb.png)

**Comment by enginehouse** [comment]
True and technically it should be wrapped in a <thead> too - I was thinking that perhaps there might not be someone too technical adding this code and therefore to make it work with the most basic table formatting in case they were not able to implement the proper table html

**Comment by enginehouse** [comment]
Fixed in content
