### ISSUE TITLE
Search results page - accessibility - screenreaders read number of search results as 'search results s'

### ISSUE THREAD

**Issue by Dan-KeduTesting** [Buckinghamshire-Digital-Service/hr-service-desk-alpha#174]
see screenshot

due to "s" being on a seperate line from "result" screenreaders read it out as "result s"

fix:
s should not be on separate line 

![Search_results_page_-_accessibility_-_screenreaders_read_number_of_search_results_as_'search_results_s'](https://user-images.githubusercontent.com/2722522/65871483-6b753400-e376-11e9-82a1-249d995dace5.png)

**Comment by enginehouse** [comment]
It's not technically on a different line - see attached:

![Screenshot 2019-09-30 at 11 37 14](https://user-images.githubusercontent.com/5637994/65871642-c4dd6300-e376-11e9-93dd-8aec75f2fd66.png)

I can see a way to fix it though
