### ISSUE TITLE
Search - accessibility - when you tab to submit search icon screenreaders read out 'blank'

### ISSUE THREAD

**Issue by Dan-KeduTesting** [Buckinghamshire-Digital-Service/hr-service-desk-alpha#178]
see screenshot for code with issue.

i guess its because the "submit search" text is within a span, does it need to be in a span?

**Comment by enginehouse** [comment]
@Dan-KeduTesting it uses a generic icon generator component for consistency so comes wrapped in a span - I can take it out though if it is causing trouble

**Comment by Dan-KeduTesting** [comment]
yeah please take it out

by the way, its also an issue on homepage search textbox button and search page textbox button

**Comment by Dan-KeduTesting** [comment]
this is still an issue. it now contains no text within the button
