### ISSUE TITLE
Nav - accessibility -  search button has 2 labels 

### ISSUE THREAD

**Issue by Dan-KeduTesting** [Buckinghamshire-Digital-Service/hr-service-desk-alpha#22]
see screenshot, there should only be 1 search label (currently screen readers read out "Search Search")
![Nav_-_accessibility_-__search_button_has_2_labels](https://user-images.githubusercontent.com/2722522/64777405-fd490880-d551-11e9-95b5-67f677183df9.png)

**Comment by enginehouse** [comment]
Fixed

**Comment by Dan-KeduTesting** [comment]
passed testing
