### ISSUE TITLE
Expandable panels - accessibility - when panel is collapsed links within tab currently still in the tab order

### ISSUE THREAD

**Issue by Dan-KeduTesting** [Buckinghamshire-Digital-Service/hr-service-desk-alpha#23]
This is an issue on https://d2r8w0gkpz98vq.cloudfront.net/time-off-sick/
in the expandable panel "Frequent illness" there is a link, if you tab through the page its still on the tab index when collapsable is colapsed

FIX:
add "hidden" to the content panel div when collapsed + remove "hidden" when expanded

As per example:
https://www.w3.org/TR/wai-aria-practices/examples/accordion/accordion.html

![link_that_still_in_tab_index_when_collapsed](https://user-images.githubusercontent.com/2722522/64784031-11e0cd00-d561-11e9-93bb-30d194b16c20.png)

**Comment by Dan-KeduTesting** [comment]
failed testing

on page load the div does not have "hidden"

**Comment by enginehouse** [comment]
Re-applied will push a build
