### ISSUE TITLE
Footer - accessibility - best practice is to put role=contentinfo on the <nav>

### ISSUE THREAD

**Issue by Dan-KeduTesting** [Buckinghamshire-Digital-Service/hr-service-desk-alpha#25]
some assistive technology does not understant <nav> so role=contentinfo is needed as well

**Comment by enginehouse** [comment]
@Dan-KeduTesting - are you saying you can have two role attributes??

**Comment by Dan-KeduTesting** [comment]
Yes, although believe one is a role and the other is a landmark
