### ISSUE TITLE
Footer - accessibility - labels on footer links is not needed 

### ISSUE THREAD

**Issue by Dan-KeduTesting** [Buckinghamshire-Digital-Service/hr-service-desk-alpha#26]
see screenshot

its especially an issue for email (there is no need to refer to it as  "Footer email contact" which is a bit confusing)

![Footer_-_accessiblity_-_labels_on_fotter_links_is_not_needed](https://user-images.githubusercontent.com/2722522/64787299-57ed5f00-d568-11e9-8b4e-ebb8c455905d.png)

**Comment by enginehouse** [comment]
Fixed with 4b5ea70c Google analytics - these are an artifact of that issue
