### ISSUE TITLE
Footer - accessibility - hr needs aria-hidden=true 

### ISSUE THREAD

**Issue by Dan-KeduTesting** [Buckinghamshire-Digital-Service/hr-service-desk-alpha#27]
currently screen readers read out hr as "separator" 

![Footer_-_accessibility_-_hr_needs_aria-hidden=true](https://user-images.githubusercontent.com/2722522/64789358-1eb6ee00-d56c-11e9-9518-918b4610e587.png)

**Comment by enginehouse** [comment]
Fixed with 4b5ea70c Google analytics
