### ISSUE TITLE
Nav - accessibility - on  mobile menu remove 'home' 

### ISSUE THREAD

**Issue by Dan-KeduTesting** [Buckinghamshire-Digital-Service/hr-service-desk-alpha#28]
its a burdon for screenreader users

everyone knows selecting logo takes to homepage

![Nav_-_accessibility_-_on__mobile_menu_remove_'home'](https://user-images.githubusercontent.com/2722522/64793421-ee268280-d572-11e9-9140-a15425f5e4eb.png)

**Comment by enginehouse** [comment]
Fixed with 4b5ea70c Google analytics
