### ISSUE TITLE
Remove google analytic things that made it through to mark-up

### ISSUE THREAD

**Issue by Dan-KeduTesting** [Buckinghamshire-Digital-Service/hr-service-desk-alpha#29]
see screenshot for things in question 

![Remove_google_things_2](https://user-images.githubusercontent.com/2722522/64793490-09918d80-d573-11e9-80b7-413359c35abb.png)
![Remove_google_things](https://user-images.githubusercontent.com/2722522/64793495-0b5b5100-d573-11e9-846d-3023869144b5.png)

**Comment by enginehouse** [comment]
Fixed with 4b5ea70c Google analytics

**Comment by Dan-KeduTesting** [comment]
passed testing
