### ISSUE TITLE
Downloads page - h2 heading not displayed in correct font (on windows)

### ISSUE THREAD

**Issue by Dan-KeduTesting** [Buckinghamshire-Digital-Service/hr-service-desk-alpha#54]
see screenshot

found in chrome, but issue in ff, ie, edge

Also an issue with bottom link of each section 

![Downloads_page_-_h2_heading_not_displayed_in_correct_font_(on_windows)](https://user-images.githubusercontent.com/2722522/65318712-10815700-db96-11e9-98b4-e6945350c3ef.png)

**Comment by enginehouse** [comment]
Fixed now
