### ISSUE TITLE
Homepage - to much vertical margin above and below intro text ('find answers you need...')

### ISSUE THREAD

**Issue by Dan-KeduTesting** [Buckinghamshire-Digital-Service/hr-service-desk-alpha#59]
suggest we make it 50px  desktop + 25px mobile

see screenshot for margin in question 

![Homepage_-_to_much_vertical_margin_above_and_below_intro_text_('find_answers_you_need ')](https://user-images.githubusercontent.com/2722522/65321401-02ced000-db9c-11e9-8ffd-a24526e2553e.png)

**Comment by enginehouse** [comment]
Looks ace apparently says Derek : )))
