### ISSUE TITLE
Homepage - at bottom of white panels the margin in too small (+ inconsistent with top margin)

### ISSUE THREAD

**Issue by Dan-KeduTesting** [Buckinghamshire-Digital-Service/hr-service-desk-alpha#60]
can we make it 35px to be the same as top margin on desktop + 30px on mobile (currently on mobile margin above panel title is way to small)

see screenshot for margin in question 

![Homepage_-_at_bottom_of_white_panels_the_margin_in_too_small_(+_inconsistant_with_top_margin)](https://user-images.githubusercontent.com/2722522/65321584-7ec91800-db9c-11e9-8749-206756b6cf61.png)

**Comment by enginehouse** [comment]
It's a consistent padding all the way around - looks better. Going to leave this one til last
