### ISSUE TITLE
Homepage - on hover links of section links it should get an underline

### ISSUE THREAD

**Issue by Dan-KeduTesting** [Buckinghamshire-Digital-Service/hr-service-desk-alpha#61]
see screenshot for link in question 

![Homepage_-_on_hover_links_of_section_links_it_should_get_an_underline](https://user-images.githubusercontent.com/2722522/65321679-bcc63c00-db9c-11e9-818b-8762e0ca939a.png)

**Comment by enginehouse** [comment]
Reversed now - underline then on hover remove underline
