### ISSUE TITLE
Homepage - panel description text is too small

### ISSUE THREAD

**Issue by Dan-KeduTesting** [Buckinghamshire-Digital-Service/hr-service-desk-alpha#63]
should it be 16px?

also on mobile the line hight is too big

![Homepage_-_panel_description_text_is_too_small](https://user-images.githubusercontent.com/2722522/65322085-bd130700-db9d-11e9-836f-79e4f00e69eb.png)

**Comment by enginehouse** [comment]
![Screenshot 2019-09-25 at 15 24 39](https://user-images.githubusercontent.com/5637994/65610017-9cd1b680-dfa8-11e9-9af8-519c698b0412.png)

Looks fine now...?

**Comment by Dan-KeduTesting** [comment]
yep
