### ISSUE TITLE
Homepage - too much margin above and below 'go to download index'

### ISSUE THREAD

**Issue by Dan-KeduTesting** [Buckinghamshire-Digital-Service/hr-service-desk-alpha#64]
can we make it a consistent 50px above and below please on desktop + 25px on mobile

![Homepage_-_too_much_margin_above_and_below_'go_to_download_index'](https://user-images.githubusercontent.com/2722522/65322198-08c5b080-db9e-11e9-96f8-ec3beaa2f7c8.png)

**Comment by enginehouse** [comment]
I chatted to Derek and he said he likes this better : )
