### ISSUE TITLE
Homepage - 'go to download index' link style needs changing

### ISSUE THREAD

**Issue by Dan-KeduTesting** [Buckinghamshire-Digital-Service/hr-service-desk-alpha#65]
changed neeeded:
- link should be underline + on hover remove underline
- link should be green
- text size too big

![Homepage_-_'go_to_download_index'_link_styles_incorrect](https://user-images.githubusercontent.com/2722522/65322255-34489b00-db9e-11e9-9042-039842575601.png)

**Comment by enginehouse** [comment]
Apparently text size is fine according to Derek - more visible and sits better with the icon size
