### ISSUE TITLE
homepage -accessibility - other area' links dont have a focus state in ie11

### ISSUE THREAD

**Issue by Dan-KeduTesting** [Buckinghamshire-Digital-Service/hr-service-desk-alpha#71]
add a custom focus for all links?
![homepage_-accessibility_-_other_area'_links_dont_have_a_focus_state_in_ie11](https://user-images.githubusercontent.com/2722522/65327530-141fd880-dbac-11e9-954c-81a18f07bc80.png)

**Comment by enginehouse** [comment]
They have an outline - is that what you mean? @Dan-KeduTesting

**Comment by Dan-KeduTesting** [comment]
yeah they have outline in chrome but not in ie11!

**Comment by enginehouse** [comment]
Oh ok gotcha! I'll sort it

**Comment by enginehouse** [comment]
FIxed with 6be38774 Outline
