### ISSUE TITLE
details template - copy in expandable is too small + link size too small

### ISSUE THREAD

**Issue by Dan-KeduTesting** [Buckinghamshire-Digital-Service/hr-service-desk-alpha#73]
see image for screenshot vs design

![details_template_-_copy_in_expandable_is_too_small_+_link_size_too_small](https://user-images.githubusercontent.com/2722522/65329317-1f750300-dbb0-11e9-8972-ebd092dd5add.png)

**Comment by enginehouse** [comment]
Fixed with 66ae662d Fix: #72, #75, #76 - collapsible text

**Comment by Dan-KeduTesting** [comment]
failed testing

the link text size is still to small. links text size is smaller than other text size. suggest its made the same text size or bigger (as per designs)
