### ISSUE TITLE
details template - when expanding panel and re-sizing some text may get cut off

### ISSUE THREAD

**Issue by Dan-KeduTesting** [Buckinghamshire-Digital-Service/hr-service-desk-alpha#77]
this may be an issue for some tables changing from landscape to portrait

![details_template_-_when_expanding_panel_and_re-sizing_some_text_may_get_cut_off](https://user-images.githubusercontent.com/2722522/65331058-dde65700-dbb3-11e9-9763-2357699f3272.png)

**Comment by enginehouse** [comment]
Edge case - and reopening the collapsible will sort this (very few people resize browser windows on desktop) 
Can sort if it becomes noticeable for users
