### ISSUE TITLE
Menu - on mobile menu the menu link text is too big

### ISSUE THREAD

**Issue by Dan-KeduTesting** [Buckinghamshire-Digital-Service/hr-service-desk-alpha#83]
see image of screenshot vs design

![Menu_-_on_mobile_menu_the_menu_link_text_is_too_big](https://user-images.githubusercontent.com/2722522/65411211-30a65580-dde4-11e9-995c-fb00a30414a8.png)

**Comment by enginehouse** [comment]
This is reusing a large font size already declared so going to keep using it - we onyl have three links so not running out of space
