### ISSUE TITLE
Menu - on mobile menu the close menu icon is too small

### ISSUE THREAD

**Issue by Dan-KeduTesting** [Buckinghamshire-Digital-Service/hr-service-desk-alpha#84]
see image of screenshot vs design

can the touch area be 45 x 45 px (e.g. larger than the icon)

also an issue for search mobile page

![Menu_-_on_mobile_menu_the_close_menu_icon_is_too_small](https://user-images.githubusercontent.com/2722522/65411362-94308300-dde4-11e9-8493-578201eb76b5.png)

**Comment by enginehouse** [comment]
It is actually has a 52 X 52 px hit area but it is transparent - i think this is fine
