### ISSUE TITLE
All pages - 'meta title' in contentful is not being used as browser title

### ISSUE THREAD

**Issue by Dan-KeduTesting** [Buckinghamshire-Digital-Service/hr-service-desk-alpha#95]

**Comment by enginehouse** [comment]
It is - I think you were viewing the wrong one - tested

**Comment by Dan-KeduTesting** [comment]
failed testing, see screenshot below in contentful for about page and see show it does not match up to browser title 

![html_showing_title](https://user-images.githubusercontent.com/2722522/65714207-91f35080-e092-11e9-9dd7-5b09a4f4c426.png)

![contenful_-_meta_title](https://user-images.githubusercontent.com/2722522/65714229-991a5e80-e092-11e9-91a8-b5b6d7ba28cd.png)

**Comment by enginehouse** [comment]
Doh! Sorry you are correct : ) - I changed the wrong one :  |

Fixed now
